// <auto-generated />
using System;
using System.Collections.Generic;
using CsvSerializer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CsvSerializer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DatasetId")
                        .HasColumnType("bigint")
                        .HasColumnName("dataset_id");

                    b.Property<bool>("EncodingDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("encoding_detected");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("FileReceived")
                        .HasColumnType("boolean")
                        .HasColumnName("file_received");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<int>("RowsDuplicates")
                        .HasColumnType("integer")
                        .HasColumnName("rows_duplicates");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_inserted");

                    b.Property<int>("RowsInvalid")
                        .HasColumnType("integer")
                        .HasColumnName("rows_invalid");

                    b.Property<int>("RowsNormalized")
                        .HasColumnType("integer")
                        .HasColumnName("rows_normalized");

                    b.Property<int>("RowsScanned")
                        .HasColumnType("integer")
                        .HasColumnName("rows_scanned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("StructureDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("structure_detected");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportJobEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("import_job_events", (string)null);
                });

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportedDataset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Delimiter")
                        .HasColumnType("text")
                        .HasColumnName("delimiter");

                    b.Property<string>("DetectedEncoding")
                        .HasColumnType("text")
                        .HasColumnName("detected_encoding");

                    b.Property<int>("DuplicateRows")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_rows");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.PrimitiveCollection<List<string>>("HeaderRowJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("header_row_json");

                    b.Property<int>("InsertedRows")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_rows");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_rows");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("imported_datasets", (string)null);
                });

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportJob", b =>
                {
                    b.HasOne("CsvSerializer.Api.Models.ImportedDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportJobEvent", b =>
                {
                    b.HasOne("CsvSerializer.Api.Models.ImportJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CsvSerializer.Api.Models.ImportJob", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
